---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgBwV8iHR97f51zu+HQjVJLcLJ0ki3iHoEBOgh3BAORS/3Pn3Hgr2LOiFDBbZJ3oiT4qvYEglF/lvUmigYL1nJ/Ud85g5dyT92a+M/cIlvLv3yEmHrbqrMt10BPZ+ovZ5T9EJQOUMIsDx+302Gz8NIN0uTwsGGg9IDOfgQU42LVE4HxhfAu8haWkM8dpUhc/gewG10ZG8GQ3zMozLfmPczbtuhLV7qWbKfKcDYyRtif3fm7rCJedg/V/wUoA1hSGMhu/Ytqz1x4Hga8jJngBO1mZxDosm2LYYHafE0dLnRkIt7Zbor6K+wIdyRBuNzRyBDbaNKxECSp3XSTifPNPjMuYlLWTSQgkX/mw5p92tByL/jA79lEtzMQXM9lGNkzo7MTJ3s1yk7HabYRJU+YjHRmlIG8N+zGqVlJLK6jSLQOwaWgSKrRW7FtSJfWr6tiEzivTL+Me+U94GENEJSEJxEq/4qRIw0Gu3YDTgHmv+5Jl6uNnoMu5T13UpUG1LxeAIm9eObG55ZzSAxlmN8+aZzGDr44u7RBQgnzH1qD+yuNpR5ROX/FsAmSwRbwN1ZkqzBfhITKXTVleq4UB+XWjGOVIMaHz7cq2+pkNcEiYvrsKtyHkTwJiwmaMTuCmZM3KJDv2i2M3tyCBqSJUsT3ICpn9yI9hXfRqrY5P9mUIxQI4aDM1DMgu94UQCAztcT2YqtuULdDkrIMttJsQGESKqKi6hh0ZuYtA8dJ//Ul8fwwZORA4mwAT1374c+COBgV25f0v+zzMb0KGz71sbYeKhEMa9j9fFhnE
  template:
    metadata:
      name: alertmanager-discord
      namespace: monitoring
