---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgCWvwJEzOkNc5tFYni2FBS7isIPotJx2FeAwsXyVODqgWE6/3RrU0vJKpo1lk+Gg342yk4DGobzotn+M6n0yvP99qWePP4vXH2jHaNcum5/NouXjSqWAZ1UbtIJwBpen9i0+cuuL4iJy5FXaeO0ASahHtVnweRNB0OqYupq8ZHK0j8pimJEV5yB7kln0ni6OUYqofLnxczl47ITXfzkYIFz3gJ4JD88rdue6UUMa3zUSb/5q3afxRXIJQ+XHpG2yWBCZblDtWyOdpV9GQBFXSItIKhaiTWy/1fIGZr9ChXyKbEuhkHmgH7h/dYM9LfcnucdM+4bqlKHZL45kaSi1abCZfm6LdN7ojW+y5s2Lf6/syRvgYuY45WBriDCw8edP3AyIfACymlspvooj4pohyZb9hn/v9Y6BKJsK9ghgmooY4Z3rgYdOLXRb38xsyhTfMhq5nK3JzUYX249Nome3OrH9WY1h86ocxfPo4BzTeKDO3dQEBd6SSpLNGy9UPrI18lN9Il45Mc1bXfIWMzsJ0b2Z/i/7hAwbuO1CTKfY1O/LuSrDBvTV7ajGaSAmrJSu88y/3BaDBjaMII5GBUAqXd5NBewM9+/ggGw7c7xWtJlBI8xpFN9k5/0Og3fCzAgWkjjBVVsbEFkpZFQaBNWoRsBfgT5JvIfFZhNfukPEf/rmmfEAPYnnL5H6H2yR0q019bxifX/xRYmmtAN8RLlI4kbHuLqaXga4d0Fi1o3Xno3Iy+LmwGuNHm2n0EuMFKET5LDdGM1n3Qu2UA1rA6DCueNWlZOJkfddHdtMN8pUzGJhmnCgOia3NyoXst05eGk4LIgD8mWvewfhEHnBlaq2vrY4wTxheRGdLx/
  template:
    metadata:
      name: alertmanager-discord
      namespace: monitoring
