---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgCiajI7Mpn575EMcrl4Di66d9m+VkTADwPzQohqZHf/einBzGEZY2us+WPUiiuJ8Rx694IVkTJHU3EPRNFBOCh+mA3iXmxVY/hqdvIVlHMvQ1qxU6SmqQnFaI9arpo1LK0Nux3sYxAfyFg9vYhWelXYFUhlY+MCbWWhg9AnqTN7Vhdb0M61h3/w7XyJD12tQnWDGOHh2UL7xQFJwIcGFytrH8M+6BeVEEqFYaFvTtcNvaMIFMULR1I5xTicWLCeHmi3tKEfRqV3QsAaHppN86SZXsaRq06+omgH82R9cjZsAU8zt7Oc7rKWws8dcIFAIgSygqRBFvhw0rPpWvNlpIBC2o0U9tnRc8uwSbE8kGNnuhvfbXF2bv5lFdecfyuFaGuqyQWkHsuHjPCJWhopp7WUYDTmo2SKr2MSiBqs/q3vfPKiTN7qQplN6yKcmyuOP8rqzBq0UC11+c92tmNkDytm6syIwwC2PsWKQBXpYcVuUtMA2M1HLoHR7mpFHH72z6C4RwrWIgxmHyvfybYBQrhCPqgraUpYmmrNU1E/j3qBpW6LTiPjfaDNvF1tGK55ReFRK0KrYMs8b+tx9zLXwluB5/bIi780MAenNhWuR+PnZrT+kKALyUBD75I9685B+qJlui9s4spWfGC0EbgIDtTjAPTXmpaY7aBGgBiUyCsL/HZQZc0m+G7vA5fb8RgcPfOENLUlnhdGMwYhlSFOLOjy4Dt6xdjzhvU=
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
